### ISSUE TITLE
Local stream error

### ISSUE THREAD

**Issue by MoonDragon-MD** [ra101/LBRY-VLC-Playlist-Parser#1]
Hello, I have now tried the plugin with vlc 3.0.9.2 on ubuntu 20.04, setting the log view I have the following errors:
`﻿-- logger module started --
main: playlist is empty
lua: Using roosterteeth plugin
http error: local stream 1 error: Cancellation (0x8)
access error: HTTP 404 error
http error: local stream 1 error: Cancellation (0x8)
lua: Using roosterteeth plugin
http error: local stream 1 error: Cancellation (0x8)
access error: HTTP 404 error
http error: local stream 1 error: Cancellation (0x8)`
 As you see I tried with two different videos, maybe lbry changed something

**Comment by ra101** [comment]
A problem occured with my system too. maybe lbry did change something, I tweaked the code a lil bit, it is now working in my system, check your too.

**Comment by MoonDragon-MD** [comment]
Now it works perfectly! Thank you very much
